### ISSUE TITLE
pyxis doesn't use environment variables defined in enroot .env files

### ISSUE THREAD

**Issue by kcgthb** [NVIDIA/pyxis#46] opened 2021-05-13 00:10 UTC
Hi!

Let's say you have an `enroot` `.env` file that references an environment variable:
```bash
$ cat /etc/enroot/environ.d/test.env
TEST_VAR=${TEST_VAR}
```

When using `enroot` directly, the environment variable in the container is set to what it's been set on the host:
```bash
$ enroot start debian sh -c 'echo TEST_VAR=${TEST_VAR}'
TEST_VAR=
$ TEST_VAR=foobar enroot start debian sh -c 'echo TEST_VAR=${TEST_VAR}'
TEST_VAR=foobar
```

With Slurm, when using `srun`, the environment variable is also correctly passed to the compute node:
```bash
$ TEST_VAR=foobar srun sh -c 'echo TEST_VAR=${TEST_VAR}'
TEST_VAR=foobar
```

And when running `enroot` through `srun`, things work too:
```bash
$ TEST_VAR=foobar srun enroot start debian sh -c 'echo TEST_VAR=${TEST_VAR}'
TEST_VAR=foobar
```

But when using `pyxis`, it looks like the `enroot` `.env` file is ignored:
```bash
$ TEST_VAR=foobar srun --container-image=debian sh -c 'echo TEST_VAR=${TEST_VAR}'
pyxis: importing docker image ...
TEST_VAR=
```

I assume this is because when `pyxis` calls `enroot`, it is in a context where `TEST_VAR` is not defined, so it does parse the `/etc/enroot/environ.d/test.env` file, but substitutes an empty value to the variable.

I wanted to verify that by using a default value fallback in the variable definition, but it looks like `enroot` may be parsing this literally :smile:. So it doesn't prove the "undefined environment  variable" hypothesis, but it does indicate that the `/etc/enroot/environ.d/test.env` file is used:
```bash
$ cat /etc/enroot/environ.d/test.env
TEST_VAR=${TEST_VAR:-fallback}
$ TEST_VAR=foobar srun --container-image=debian sh -c 'echo TEST_VAR=${TEST_VAR}'
pyxis: importing docker image ...
TEST_VAR=${TEST_VAR:-fallback}
```

### Use case

We typically define a number of environment variables to point to various storage locations for our users. Those paths depend on a number of factors and are different for each user (exactly like `$HOME`). We would like to be able to automatically pass those environment variable to containers executed via `pyxis`/`enroot` and have the file systems mounted as well.

The goal is to have something like this:
```bash
$ cat /etc/enroot/environ.d/scratch.env
SCRATCH=${SCRATCH}

$ cat /etc/enroot/mounts.d/scratch.fstab
${SCRATCH}              ${SCRATCH}        none    x-create=dir,bind,rw,nosuid
```
and to have the user-specific `$SCRATCH` folder automatically mounted in containers. 

Although all of that works well when containers are started by `enroot` directly, it doesn't work when they're started through `pyxis`, as the `$SCRATCH` environment variable is not defined when the container is initialized.

**Comment by 3XX0** [comment] 2021-05-13 00:56
Pyxis does export environment variable from the command line, however it won't override any existing one (in this case the one set in the enroot config).
We already had this debate several time, so we should probably add some way of expressing that eventually.

In your particular example, this is a little more tricky because the variable references itself, so it could be supported if the environment wasn't filtered at startup, right @flx42? IIRC we filter the environment initially so that users have less chance of messing up the container startup.

As for `TEST_VAR=${TEST_VAR:-fallback}`, enroot doesn't support shell substitution in configuration files yet.
This is more of a `/etc/environment` with support for simple substitutions.

**Comment by kcgthb** [comment] 2021-05-13 01:21
Noted for shell substitutions in `enroot` configuration files, I was just trying to push my luck. :)
It's already great that variables are supported at all! 

For `pyxis` filtering out the environment at startup, that may be more of an issue, though. I can see plenty of cases where a sysadmin will want to have env vars passed to the users' containers, and if the variables set in `enroot` `.env` files are not passed to the `pyxis` environment, that will make things difficult.

For instance, another case to illustrate this: if the sysadmin defines a user-specific `ENROOT_DATA_PATH` in `/etc/enroot/enroot.conf` using an environment variable, there's no problem when `enroot` is called directly, but `pyxis` can't resolve that variable and fails to run the container:

```
$ grep ENROOT_DATA_PATH /etc/enroot/enroot.conf
ENROOT_DATA_PATH            ${SCRATCH}/.enroot/data

$ srun --container-image=debian --pty bash
pyxis: importing docker image ...
slurmstepd: error: pyxis: container start failed with error code: 1
slurmstepd: error: pyxis: printing contents of log file ...
slurmstepd: error: pyxis:     /usr/bin/enroot: line 44: SCRATCH: unbound variable
slurmstepd: error: pyxis:     /usr/bin/enroot: line 44: SCRATCH: unbound variable
slurmstepd: error: pyxis:     /usr/lib/enroot/runtime.sh: line 206: _lock: No space left on device
slurmstepd: error: pyxis: couldn't start container
slurmstepd: error: pyxis: if the image has an unusual entrypoint, try using --no-container-entrypoint
slurmstepd: error: spank: required plugin spank_pyxis.so: task_init() failed with rc=-1
slurmstepd: error: Failed to invoke spank plugin stack
srun: error: sh02-01n60: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=24250082.1
```

The failure is actually more about `No space left on device`, but it's because it must be falling back to `$XDG_DATA_HOME` (which doesn't have enough free space) instead of using the `$ENROOT_DATA_PATH` defined in `enroot.conf`.

Maybe there could be a mode where `pyxis` would not filter out the environment, so those variables could be used in `enroot` configuration files? Like another [plugstack option](https://github.com/NVIDIA/pyxis/wiki/Setup#slurm-plugstack-configuration)?

**Comment by 3XX0** [comment] 2021-05-13 02:06
Yeah there is definitely a case for the startup environment, @flx42 do you recall what failed when we weren't filtering?
Note that this only applies to environment set in the context of the `srun` command (so things like the shell environ and `--export`), harcoded variables in `.env` files will still work since it's enroot that is reading those files (e.g. `FOO=bar` will show up).

The override of existing variables is a little more touchy though, since for example you don't want to override `PATH` with the host one, so it would have to be a whitelist of some sort.

**Comment by flx42** [comment] 2021-05-13 04:18
> In your particular example, this is a little more tricky because the variable references itself, so it could be supported if the environment wasn't filtered at startup, right @flx42? IIRC we filter the environment initially so that users have less chance of messing up the container startup.

Correct, that's the reason here. The initial goal was to have the system administrator control most of the container configuration happening in pyxis, to have container creation/startup consistent and reproducible for all users. This is to avoid issues when a user has weird values in their PATH, LD_LIBRARY_PATH or enroot variables, it would cause `srun --container-image` to fail.

In the example with `TEST_VAR`, you would have to set the value of `TEST_VAR` for slurmd, for example in the systemd unit file, it will be passed to enroot.
That won't work when you need different values for different users, like `SCRATCH`. In this situation, yes we would need a new plugstack option to pass the job environment and not the admin-controlled slurmd environment. However, for the particular case of `ENROOT_DATA_PATH`, you have more freedom in what you can do in `enroot.conf`, for instance the following would work:
```
ENROOT_DATA_PATH /scratch/$(id -u)
```
But I suppose that won't integrate well with your existing setup.

> Yeah there is definitely a case for the startup environment, @flx42 do you recall what failed when we weren't filtering?

Now that we are doing container creation and start in `slurm_spank_task_init` (since 0.8.0), we do have access to more relevant environment variables (for instance we were able to switch to the enroot hook for PMIx support). But for example we don't want to pass `SLURM_LOCALID` or `SLURM_PROCID` to enroot, otherwise all ranks on the same node will end up with the same value of `RANK` and `LOCAL_RANK`, as we start the container only once but the environment is used by all local ranks:
https://github.com/NVIDIA/enroot/blob/master/conf/hooks/extra/50-slurm-pytorch.sh#L32-L37

> The override of existing variables is a little more touchy though, since for example you don't want to override PATH with the host one, so it would have to be a whitelist of some sort.

Right... this is https://github.com/NVIDIA/pyxis/issues/26, but I don't have a good solution so far.

**Comment by kcgthb** [comment] 2021-05-13 18:33
Right, I get the need to filter out the environment, that makes complete sense. And I guess I can get around the issue for `ENROOT_DATA_PATH` with the workaround you suggested, but for other environment variables, that may not work that well, indeed: I can't really 'hardcode" the value of those variables in a global `enroot` `.env` file, as they will be different for each user.


Right now, my main confusion point comes from the difference of behavior between `enroot` and `pyxis` regarding environment variables.

If I don't define `TEST_VAR` in `enroot` conf files, when I call `enroot` directly, the value of environment variable is not passed from the user environment on the host to the container:
```
compute$ grep -r TEST_VAR /etc/enroot/* ~/.config/enroot/
compute$ TEST_VAR=foobar enroot start debian sh -c 'echo TEST_VAR=$TEST_VAR'
TEST_VAR=
```
So I declare that environment variable in `enroot` configuration, and then it's passed to the container:
```
compute$ mkdir ~/.config/enroot/environ.d/
compute$ echo 'TEST_VAR=${TEST_VAR}' >> ~/.config/enroot/environ.d/test.env
compute$ TEST_VAR=foo enroot start debian sh -c 'echo TEST_VAR=$TEST_VAR'
TEST_VAR=foo
compute$ TEST_VAR=bar enroot start debian sh -c 'echo TEST_VAR=$TEST_VAR'
TEST_VAR=bar
```

But when `enroot` is called through Slurm and `pyxis`, the environment is filtered, and the environment variable is lost:
```
login$ TEST_VAR=foo srun --container-image=debian sh -c 'echo TEST_VAR=$TEST_VAR'
pyxis: importing docker image ...
TEST_VAR=
```

Now, if I **remove** the envvar declaration from the `enroot` config, the variable **is** passed to the container through `pyxis`... :thinking:
```
login$ rm ~/.config/enroot/environ.d/test.env
login$ grep -r TEST_VAR /etc/enroot/* ~/.config/enroot/
login$ TEST_VAR=foo srun --container-image=debian sh -c 'echo TEST_VAR=$TEST_VAR'
pyxis: importing docker image ...
TEST_VAR=foo
```
(`$HOME` is shared, so `~/.config/enroot` is the same on login and compute)

So basically, `enroot` and `pyxis` are behaving in opposite ways:
* if a 'dynamic' env var is defined in `enroot` conf files, `enroot` passes it to the container, but not `pyxis`
* if it's not defined in `enroot` conf files, `enroot` doesn't pass it to the container, but `pyxis` does.

See how I'm confused here? :)

My naive idea would be to maybe construct some sort of envvar allow-list for `pyxis` from what's defined in `enroot`'s .env` files?  That would allow to still continue to filter the environment and prevent against passing `PATH` or `SLURM` environment variables to the container, but allow sysadmins to declare a set of variables that should be passed to the container from the user environment in all cases. 

I guess what I'm looking for is a way to set user-specific environment variables in containers, in a way that works reliably and similarly whether `enroot` is called directly or through `pyxis`. Hope that makes sense! :)

**Comment by flx42** [comment] 2021-05-13 19:07
> Now, if I remove the envvar declaration from the enroot config, the variable is passed to the container through pyxis... 🤔
> [...]
> if a 'dynamic' env var is defined in enroot conf files, enroot passes it to the container, but not pyxis


Yes, that is because the variable references itself. So what happens in pyxis is equivalent to this:
```
$ env --unset TEST_VAR enroot start debian env | grep TEST_VAR
TEST_VAR=
```
The variable is set inside the container, but to the empty string. So this will take precedence over `TEST_VAR=foo` from the job (the environment from the container always has precedence). This is a nasty edge case for sure :)

For your use case, you probably don't want to set `TEST_VAR` inside the container if it wasn't set originally, i.e. you want a hook like the following instead:
```
#! /usr/bin/env bash

set -eu

source "${ENROOT_LIBRARY_PATH}/common.sh"

if [ -v TEST_VAR ]; then
    printf "TEST_VAR=%s\n" "${TEST_VAR}" >> "${ENROOT_ENVIRON}"
fi
```

> if it's not defined in enroot conf files, enroot doesn't pass it to the container, but pyxis does.

True, enroot and pyxis behave differently here. Pyxis being a Slurm plugin, we want to preserve the environment of the job by default, otherwise it could be confusing in relation to `srun --export=ALL` (which is the default behavior).

> I guess what I'm looking for is a way to set user-specific environment variables in containers, in a way that works reliably and similarly whether enroot is called directly or through pyxis. Hope that makes sense! :)

Yes that makes sense, I think we can indeed add this feature through another plugstack option. Something like the following I suppose:
```
required /usr/local/lib/slurm/spank_pyxis.so enroot_env=SCRATCH,TEST_VAR
```
Would that work for you?

**Comment by kcgthb** [comment] 2021-05-13 20:38
> The variable is set inside the container, but to the empty string. 

Yep, I see how that's actually happening: the variable is filtered out before `enroot` gets to process its own configuration files and set the container's environment. By the time it gets there, `TEST_VAR` is empty.

There's quite a number of environment-passing layers, from the user's shell, to Slurm (srun), then Pyxis and finally Enroot. Onion-like ;)

> I think we can indeed add this feature through another plugstack option. Something like the following I suppose:
> ```
> required /usr/local/lib/slurm/spank_pyxis.so enroot_env=SCRATCH,TEST_VAR
> ```
> Would that work for you?

I guess so. My only gripe would be that those environment variables would have to be listed twice in two different places (in an `enroot` `.env` file and in the `pyxis` plugstack configuration file) to get the same behavior in both cases. With the risk of the 2 lists getting out of sync and causing headaches.

I have no idea how feasible this is, but I feel like a better solution would be for Pyxis to parse the Enroot `.env` files to determine which variables are set there, and automatically preserve them when cleaning up the environment. From a user/sysadmin perspective, that would make the `pyxis`/`enroot` integration more seamless, I think.

**Comment by flx42** [comment] 2021-05-13 22:52
> Yep, I see how that's actually happening: the variable is filtered out before enroot gets to process its own configuration files and set the container's environment. By the time it gets there, TEST_VAR is empty.

extreme nitpicking: `TEST_VAR` is unset when enroot is executed by pyxis, so that's different than empty / null. It becomes empty because of `TEST_VAR=${TEST_VAR}` which indiscriminately creates a null `TEST_VAR` variable when the right hand side is unset *or* empty.

> I have no idea how feasible this is, but I feel like a better solution would be for Pyxis to parse the Enroot .env files to determine which variables are set there, and automatically preserve them when cleaning up the environment. From a user/sysadmin perspective, that would make the pyxis/enroot integration more seamless, I think.

I don't think we can do that in a reliable way.

**Comment by 3XX0** [comment] 2021-05-13 23:47
I think we could relax the filtering of the environment at startup, I don't think there are a lot of things that can mess with enroot. We can maintain a blacklist for obvious things like PATH or have this configurable in plugstack.

I tend to agree with @kcgthb that specifying it a two places kinda defeat its purpose. A blacklist instead of a whitelist might be more adequate here.

**Comment by 3XX0** [comment] 2021-05-14 00:06
And just so we're on the same page, the equivalent to what Pyxis is doing is as follow:

```
env -i <minimal_pyxis_env> enroot start debian &
enroot exec -e <srun_env if not already set> $!
```
Where `minimal_pyxis_env` is listed in https://github.com/NVIDIA/pyxis/issues/46#issuecomment-840233502

`TEST_VAR` is not in the environment of the first command, thus gets set to empty string when processing the enroot config. It is part of the `srun_env` of the second command but policy is to not override existing environment (`TEST_VAR` is set in the container bug empty) so it gets skipped

**Comment by flx42** [comment] 2021-05-14 00:41
> I think we could relax the filtering of the environment at startup, I don't think there are a lot of things that can mess with enroot. We can maintain a blacklist for obvious things like PATH or have this configurable in plugstack.

Yeah, ok, that seems reasonable to have a deny-list instead. Especially given that the list allow-list kept growing over the pyxis releases. I will take a stab at this and report if there is any problem with environment variables from the job.

**Comment by kcgthb** [comment] 2021-05-14 01:15
I think a safety deny-list would work well too. 

Accidental passing of problematic environment variables will probably be minimal, since those environment variables will still have to be defined in the `enroot` environment files to be set in the container, right? So the user environment will not be blindly passed to the container in the `srun -> pyxis -> enroot` case ; `enroot` will still set the container environment based on its config, except the "dynamic" variables will not have been unset first. It will just make `pyxis` more "transparent" and make the behavior closer to the case where `enroot` is executed directly. 

I like it :)

**Comment by flx42** [comment] 2021-05-14 01:55
> Accidental passing of problematic environment variables will probably be minimal, since those environment variables will still have to be defined in the enroot environment files to be set in the container, right?

The concern was more around the user setting environment variables breaking the `enroot import` or `enroot create`, and then complaining to the cluster admin :). It might happen after sharing a setup script or even a .bashrc with another user.

For example, the pyxis equivalent of the following, setting `ENROOT_CACHE_PATH` to a directory the user can't access:
```
$ ENROOT_CACHE_PATH=/root enroot import docker://debian
[INFO] Querying registry for permission grant
[INFO] Authenticating with user: <anonymous>
mkdir: cannot create directory ‘/root’: Permission denied
```

Another one, breaking `enroot` by having an incomplete `PATH` (this one will be solved by the default deny list):
```
$ PATH=/tmp:/usr/bin enroot start debian
/usr/bin/env: ‘bash’: No such file or directory
```

And here is an unlikely one, but that could cause subtle issues if you have a group of users sharing an image cache (by having some layers in zstd format instead of lz4):
```
$ ENROOT_ZSTD_OPTIONS='--format=zstd' enroot import docker://debian
```

There is also all the Slurm and PMI/PMIx variables, if you have the `50-slurm-pmi.sh` hook, then they will be all exposed inside the enroot container:
https://github.com/NVIDIA/enroot/blob/711dec28f6e1c7a7280f8cdb4fe711b80e84ff22/conf/hooks/extra/50-slurm-pmi.sh#L24-L26
https://github.com/NVIDIA/enroot/blob/711dec28f6e1c7a7280f8cdb4fe711b80e84ff22/conf/hooks/extra/50-slurm-pmi.sh#L64-L66

As mentioned above, we will need to deny `SLURM_PROCID` and `SLURM_LOCALID`, otherwise it will break the pytorch hook, since all local ranks on a node will get the same value of `RANK` / `LOCAL_RANK`. This can also be solved by the deny-list.

**Comment by flx42** [comment] 2021-05-19 20:42
@kcgthb I have a PR for this change here: https://github.com/NVIDIA/pyxis/pull/48

To circumvent potential issues with `ENROOT_CACHE_PATH` or `ENROOT_DATA_PATH` being set by the user, those variables are currently denied, but if the admin specified something like `ENROOT_DATA_PATH  ${SCRATCH}/.enroot/data`, then it work since `SCRATCH` will be passed.
In other words, when using pyxis, `ENROOT_DATA_PATH` will be dynamic only if the admin setup the enroot configuration file to be dynamic.

Right now the deny list is static, and perhaps too restrictive, so give it a try if you can! Perhaps a future PR will add a new plugstack argument to allow extending this deny list.

There are two caveats however.

### Caveat 1
If you use `ENROOT_DATA_PATH  ${SCRATCH}/.enroot/data` but `SCRATCH` is *not* set, then enroot will discard the configuration entry and switch to using the default value, e.g. `ENROOT_DATA_PATH        "${XDG_DATA_HOME}/enroot"`. With `enroot`, you do get a a visual cue that something went wrong:
```
$ enroot list
/usr/bin/enroot: line 49: SCRATCH: unbound variable
ubuntu
```
With pyxis you won't see this line as the enroot command still succeeds.
@3XX0 is that the expected/intended behavior?

### Caveat 2
If you use `ENROOT_DATA_PATH  ${SCRATCH}/.enroot/data`, then plugstack argument [`container_scope=job`](https://github.com/NVIDIA/pyxis/wiki/Setup#slurm-plugstack-configuration) (not the default value) won't be able to automatically cleanup named containers in the Spank job epilog, as the job environment (including `SCRATCH`) is not available in the Spank job epilog. It is the equivalent of something like the following:
```
$ SCRATCH=/tmp enroot create ubuntu.sqsh 

$ enroot remove ubuntu
/usr/bin/enroot: line 49: SCRATCH: unbound variable
[ERROR] No such file or directory: /home/fabecassis/.local/share/enroot/ubuntu
```

**Comment by kcgthb** [comment] 2021-05-20 00:30
Thanks a lot @flx42. 
That looks great, I'm gonna give it a try!

**Comment by flx42** [comment] 2021-06-04 00:04
@kcgthb did you have time to test this branch?

I've just updated the branch to deny a few more environment variables to prevent users from overriding enroot environment variables related to `enroot import` inside pyxis (of course they can set those environment variables when using enroot outside of pyxis).

**Comment by kcgthb** [comment] 2021-06-04 00:23
@flx42 sorry, I've been sidetracked. :\
I'll take a look and report back shortly.

**Comment by flx42** [comment] 2021-06-04 00:26
Thanks, no rush.

**Comment by kcgthb** [comment] 2021-06-04 22:39
Happy to report that #48 works great!

The environment variables set in the calling environment are not reset by Pyxis anymore, which opens the possibility of having sysadmin-controlled user-specific defaults (like for mount points, for instance), which is great.

Thanks!

Works great for me!

**Comment by flx42** [comment] 2021-06-07 21:28
Merged #48

**Closed by flx42** 2021-06-07 21:28 UTC

**Comment by remomomo** [comment] 2022-04-27 18:14
Hi, I'm still trying to wrap my head around the issue described above, but if I understood everything correctly, then pyxis does **not** respect configuration of `ENROOT_DATA_PATH` by the **user**. I do not have admin rights, and I run out of space on the temporary file system if I try to spin up many slurm jobs at the same time using pyxis.

If `ENROOT_DATA_PATH` cannot be defined by the user, there is no way for me to solve this issue if I want to use pyxis. That's unfortunate, because if I have to specifically use enroot-specific commands (`enroot ...`), my scripts are no longer sharable, i.e., independent of the container software being used.

Is there a way for the user to set `ENROOT_DATA_PATH` and have it be respected by pyxis?

**Comment by flx42** [comment] 2022-04-27 19:41
@remomomo sorry but there is currently no way to do that as a user, you will have to ask the admin to change the `enroot.conf`
