### ISSUE TITLE
slurmstepd: error: pyxis: seccomp filter failed

### ISSUE THREAD

**Issue by fuqingping1** [NVIDIA/pyxis#6] opened 2019-10-09 09:55 UTC
Hi Felix，
               I got this error when run the example,
  root@e:~/enroot# srun -p RTX8000 --container-image="centos" grep NAME /etc/os-release
slurmstepd: pyxis: running "enroot import" ...
slurmstepd: pyxis: running "enroot create" ...
slurmstepd: pyxis: running "enroot start" ...
slurmstepd: error: pyxis: seccomp filter failed
slurmstepd: error: spank: required plugin spank_pyxis.so: task_init() failed with rc=-1
slurmstepd: error: Failed to invoke spank plugin stack
srun: error: em-node0: task 0: Exited with exit code 1

some instructions? thanks!

**Comment by fuqingping1** [comment] 2019-10-09 10:53
I have to delete the lines: (it's OK now(to run and install software in container with srun) but I do not know whether there will be any other bad results)
ret = seccomp_set_filter();
	if (ret < 0) {
		slurm_error("pyxis: seccomp filter failed");
		goto fail;
	}

**Comment by flx42** [comment] 2019-10-09 17:13
Hi, thanks for the bug report!

Which distro are you running? `cat /etc/os-release`

Which kernel version do you have? `uname -a`

Is your kernel compiled with seccomp support? `grep SECCOMP /boot/config-$(uname -r)`

Thanks!

**Comment by flx42** [comment] 2019-10-09 17:30
Also, let's try with just `enroot`, without `pyxis`:
```
enroot import docker://ubuntu
enroot create ubuntu.sqsh
enroot start --root --rw ubuntu grep Seccomp /proc/self/status
```

**Comment by fuqingping1** [comment] 2019-10-10 01:44
the distro is Ubuntu 16.04, and CONFIG_SECCOMP_FILTER=y is supported.
also just with enroot is OK.
and I think the reason is that, with srun I submit the task to the master-node(for test also as compute node).  when I submit the task to a new compute node, it run correctly. 
thanks!

**Comment by flx42** [comment] 2019-10-11 01:58
>  and I think the reason is that, with srun I submit the task to the master-node(for test also as compute node). when I submit the task to a new compute node, it run correctly.

This is still weird, and not sure what would be the cause. Maybe the `errno` value will provide a hint so I'm printing the error in the log now: ba4e52d743774d9a107ce7c0cae13f12c75350ba

**Comment by fuqingping1** [comment] 2019-10-11 03:54
> > and I think the reason is that, with srun I submit the task to the master-node(for test also as compute node). when I submit the task to a new compute node, it run correctly.
> 
> This is still weird, and not sure what would be the cause. Maybe the `errno` value will provide a hint so I'm printing the error in the log now: [ba4e52d](https://github.com/NVIDIA/pyxis/commit/ba4e52d743774d9a107ce7c0cae13f12c75350ba)

Great， thanks！I will try latter.

**Comment by flx42** [comment] 2020-03-31 16:07
Hopefully fixed with https://github.com/NVIDIA/pyxis/commit/6bd15a0ba36e48c21bf22c494dec0ac8c6e895b6

**Closed by flx42** 2020-03-31 16:07 UTC
